import { Component, ViewEncapsulation } from '@angular/core';
import { ApexOptions } from 'ng-apexcharts';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import {MatDialog} from '@angular/material/dialog';
import {PPSService} from  'app/services/pps.service';
import { Order } from 'app/models/pps.Order.model';
import { Router } from '@angular/router';
import { RouterModule } from '@angular/router';
import { Orders } from 'app/models/pps.Pasarela.model';
import { paymentCheckOutModel } from 'app/models/pps.GenerateOrder.model';
import { animate, state, style, transition, trigger } from '@angular/animations';

export interface Tile {
    color: string;
    cols: number;
    rows: number;
    text: string;
    }

// @Component({
//     //selector     : 'masterCotizacion',
//     selector: 'app-root',
//     templateUrl  : './masterCotizacion.component.html',
//     encapsulation: ViewEncapsulation.None,
//     styleUrls: ['./app.component.scss'],
//     animations: [
//       trigger('detailExpand', [
//         state('collapsed', style({ height: '0px', minHeight: '0' })),
//         state('expanded', style({ height: '*' })),
//         transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
//       ])
//     ]
// })


@Component({
    selector: 'reporteCotizacionMaster',
    templateUrl: './masterCotizacion.component.html',
    styleUrls: ['./app.component.scss'],
    animations: [
      trigger('detailExpand', [
        state('collapsed', style({ height: '0px', minHeight: '0' })),
        state('expanded', style({ height: '*' })),
        transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
      ]),
    ],
  })

export class masterCotizacionComponent
{
    isTableExpanded = false;

  STUDENTS_DATA = [
    {
        "Id_cotize": 1,
        "NombreTipo": "AUTO",
        "NombreMarca": "DODGE",
        "NombreModelo": "AVENGER",
        "Anio": 2009,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P AC",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "MARIANO MAURILIO",
        "cotize_Apellidos": "MARQUES MORA",
        "cotize_FechaNac": "1989-10-04T00:00:00",
        "cotize_correo": "mmaumora@usa.net",
        "cotize_telefono": "8100099556",
        "cotize_CP": 64610,
        "Opciones": [
            {
                "Id_cotize": 1,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 1,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 1,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 1,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 2,
        "NombreTipo": "PICKUP",
        "NombreMarca": "HONDA",
        "NombreModelo": "RIDGE LINE",
        "Anio": 2022,
        "Vehiculo_desc": "PLATINUM AUT 3.5L 6CIL 4X4 4P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "MARDO AURELIO",
        "cotize_Apellidos": "LONGORIA JACOME",
        "cotize_FechaNac": "1989-11-19T00:00:00",
        "cotize_correo": "maureliolon@usa.net",
        "cotize_telefono": "8112065986",
        "cotize_CP": 64619,
        "Opciones": [
            {
                "Id_cotize": 2,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 2,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 2,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 2,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 3,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 4,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 5,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 6,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 7,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 8,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 9,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 10,
        "NombreTipo": "AUTO",
        "NombreMarca": "NISSAN",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 11,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 12,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 13,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 14,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 15,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 16,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 17,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 18,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 19,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 20,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 21,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 22,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 23,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 24,
        "NombreTipo": "AUTO",
        "NombreMarca": "NISSAN",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 28,
        "NombreTipo": "AUTO",
        "NombreMarca": "SUZUKI",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 30,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 31,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 32,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 33,
        "NombreTipo": "AUTO",
        "NombreMarca": "MERCEDES BENZ",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 34,
        "NombreTipo": "AUTO",
        "NombreMarca": "MERCEDES BENZ",
        "NombreModelo": "CLASE C",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 35,
        "NombreTipo": "AUTO",
        "NombreMarca": "SUZUKI",
        "NombreModelo": "VITARA",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P AC",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 36,
        "NombreTipo": "AUTO",
        "NombreMarca": "MERCEDES BENZ",
        "NombreModelo": "CLASE C",
        "Anio": 2020,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 37,
        "NombreTipo": "AUTO",
        "NombreMarca": "MERCEDES BENZ",
        "NombreModelo": "CLASE C",
        "Anio": 2020,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Guajardo",
        "cotize_Apellidos": "LONGORIA JACOME",
        "cotize_FechaNac": "1989-10-20T00:00:00",
        "cotize_correo": "juan@gmail.com",
        "cotize_telefono": "8112065986",
        "cotize_CP": 64619,
        "Opciones": [
            {
                "Id_cotize": 37,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 37,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 37,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 37,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 38,
        "NombreTipo": "AUTO",
        "NombreMarca": "BMW",
        "NombreModelo": "SERIE 3",
        "Anio": 2018,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Juan Carlos",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 39,
        "NombreTipo": "AUTO",
        "NombreMarca": "BMW",
        "NombreModelo": "SERIE 3",
        "Anio": 2018,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Juan Carlos",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 40,
        "NombreTipo": "AUTO",
        "NombreMarca": "BMW",
        "NombreModelo": "SERIE 3",
        "Anio": 2012,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P AC",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "1",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 41,
        "NombreTipo": "AUTO",
        "NombreMarca": "RENAULT",
        "NombreModelo": "ALIANCE",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "1",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 42,
        "NombreTipo": "AUTO",
        "NombreMarca": "BAIC",
        "NombreModelo": "BJ20",
        "Anio": 2020,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Alex",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 43,
        "NombreTipo": "AUTO",
        "NombreMarca": "MERCEDES BENZ",
        "NombreModelo": "560",
        "Anio": 2023,
        "Vehiculo_desc": "GT PLUS AUT 5P 6CIL 3.6L",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Rrr",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 44,
        "NombreTipo": "AUTO",
        "NombreMarca": "SUBARU",
        "NombreModelo": "TRIBECA",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "1",
        "cotize_Apellidos": "Alex",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 45,
        "NombreTipo": "AUTO",
        "NombreMarca": "PIAGGIO",
        "NombreModelo": "PORTER",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "1",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 46,
        "NombreTipo": "AUTO",
        "NombreMarca": "MG",
        "NombreModelo": "MG",
        "Anio": 2020,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "1",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 47,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 48,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 49,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "KA",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Alejando Jonguitud",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 50,
        "NombreTipo": "AUTO",
        "NombreMarca": "MAZDA",
        "NombreModelo": "MAZDA 3",
        "Anio": 2023,
        "Vehiculo_desc": "GT PLUS AUT 5P 6CIL 3.6L",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Alex JONG",
        "cotize_Apellidos": "del angel",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 51,
        "NombreTipo": "AUTO",
        "NombreMarca": "MERCEDES BENZ",
        "NombreModelo": "560",
        "Anio": 2020,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P AC",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 52,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "MUSTANG",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Joaquin",
        "cotize_Apellidos": "Guzman Loera",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 53,
        "NombreTipo": "AUTO",
        "NombreMarca": "LAMBORGHINI",
        "NombreModelo": "MURCIELAGO",
        "Anio": 2023,
        "Vehiculo_desc": "GT PLUS AUT 5P 6CIL 3.6L",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Luis",
        "cotize_Apellidos": "Hernandez",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 54,
        "NombreTipo": "AUTO",
        "NombreMarca": null,
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 55,
        "NombreTipo": "AUTO",
        "NombreMarca": "MINI",
        "NombreModelo": "CHILI",
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 56,
        "NombreTipo": "AUTO",
        "NombreMarca": "JEEP",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 57,
        "NombreTipo": "AUTO",
        "NombreMarca": "MAZDA",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 58,
        "NombreTipo": "AUTO",
        "NombreMarca": "MAZDA",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 59,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 60,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": null,
        "Anio": null,
        "Vehiculo_desc": null,
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 61,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": "SORENTO",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Lupillo",
        "cotize_Apellidos": "Rivera",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 62,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "TOPAZ",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P AC",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "2",
        "cotize_Apellidos": "2",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 63,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": "SORENTO",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 64,
        "NombreTipo": "AUTO",
        "NombreMarca": "MILES",
        "NombreModelo": "SILHOUTTE",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 65,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "KA",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "6",
        "cotize_Apellidos": "6",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 66,
        "NombreTipo": "AUTO",
        "NombreMarca": "BUICK",
        "NombreModelo": "ENVISION",
        "Anio": 2017,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 67,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "FOCUS",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P AC",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 68,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "BRONCO",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 69,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "FOCUS",
        "Anio": 2023,
        "Vehiculo_desc": "GT PLUS AUT 5P 6CIL 3.6L",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 70,
        "NombreTipo": "AUTO",
        "NombreMarca": "LAMBORGHINI",
        "NombreModelo": "HURACAN",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 71,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": "SORENTO",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 72,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": "OPTIMA",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 73,
        "NombreTipo": "AUTO",
        "NombreMarca": "MAZDA",
        "NombreModelo": "CX-3",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 74,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": "OPTIMA",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 75,
        "NombreTipo": "AUTO",
        "NombreMarca": "HONDA",
        "NombreModelo": "CIVIC",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 76,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "BRONCO",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Messi",
        "cotize_Apellidos": "Messi",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 77,
        "NombreTipo": "PICKUP",
        "NombreMarca": "TOYOTA",
        "NombreModelo": "TUNDRA",
        "Anio": 2023,
        "Vehiculo_desc": "EXT DVD R22 AUT 5P AC 8CIL QC 4X4",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Jonguitud",
        "cotize_Apellidos": "Jonguitud",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 78,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "AEROSTAR",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "lopez",
        "cotize_Apellidos": "lopez",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 79,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "B200",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "alex",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 80,
        "NombreTipo": "AUTO",
        "NombreMarca": "HONDA",
        "NombreModelo": "CROSSTOUR",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 81,
        "NombreTipo": "AUTO",
        "NombreMarca": "ALFA ROMERO",
        "NombreModelo": "156",
        "Anio": 2002,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "holq",
        "cotize_Apellidos": "holq",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 82,
        "NombreTipo": "AUTO",
        "NombreMarca": "GIANT MOTORS",
        "NombreModelo": "GF8",
        "Anio": 2020,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Pirlo",
        "cotize_Apellidos": "20/09/1987",
        "cotize_FechaNac": "1987-09-20T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 83,
        "NombreTipo": "AUTO",
        "NombreMarca": "ASTON MARTIN",
        "NombreModelo": "DB7",
        "Anio": 2002,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Camelo",
        "cotize_Apellidos": "17/06/1982",
        "cotize_FechaNac": "1982-06-17T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 84,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "CONTOUR",
        "Anio": 2020,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 85,
        "NombreTipo": "AUTO",
        "NombreMarca": "FERRARI",
        "NombreModelo": "ENZO",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Jonguitud",
        "cotize_Apellidos": "20/09/1987",
        "cotize_FechaNac": "1987-09-20T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 86,
        "NombreTipo": "AUTO",
        "NombreMarca": "MINI",
        "NombreModelo": "COOPER",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 87,
        "NombreTipo": "AUTO",
        "NombreMarca": "MCLAREN",
        "NombreModelo": "570GT",
        "Anio": 2022,
        "Vehiculo_desc": "GT PLUS AUT 5P 6CIL 3.6L",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "",
        "cotize_Apellidos": "",
        "cotize_FechaNac": "1900-01-01T00:00:00",
        "cotize_correo": "",
        "cotize_telefono": "",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 88,
        "NombreTipo": "AUTO",
        "NombreMarca": "PORSCHE",
        "NombreModelo": "BOXTER",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Alexandro",
        "cotize_Apellidos": "Del Piero",
        "cotize_FechaNac": "1973-05-09T00:00:00",
        "cotize_correo": "delpiero@gmail.com",
        "cotize_telefono": "9889876631",
        "cotize_CP": 98753,
        "Opciones": [
            {
                "Id_cotize": 88,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 88,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 88,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 88,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 89,
        "NombreTipo": "AUTO",
        "NombreMarca": "JEEP",
        "NombreModelo": "RENEGADE",
        "Anio": 2023,
        "Vehiculo_desc": "GT PLUS AUT 5P 6CIL 3.6L",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Juan",
        "cotize_Apellidos": "Suarez",
        "cotize_FechaNac": "1967-08-17T00:00:00",
        "cotize_correo": "hhh@jedjd.com",
        "cotize_telefono": "5745443433",
        "cotize_CP": 78678,
        "Opciones": [
            {
                "Id_cotize": 89,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 89,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 89,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 89,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 90,
        "NombreTipo": "AUTO",
        "NombreMarca": "AUSTIN HEALEY",
        "NombreModelo": "ROASTER",
        "Anio": 1960,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Paco",
        "cotize_Apellidos": "Stanley",
        "cotize_FechaNac": "1954-01-14T00:00:00",
        "cotize_correo": "aa@mm.com",
        "cotize_telefono": "456787878",
        "cotize_CP": 67976,
        "Opciones": [
            {
                "Id_cotize": 90,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 90,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 90,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 90,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 91,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "B200",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Jose",
        "cotize_Apellidos": "Bautista",
        "cotize_FechaNac": "1956-02-18T00:00:00",
        "cotize_correo": "alo@aol.com",
        "cotize_telefono": "9883747399",
        "cotize_CP": 98765,
        "Opciones": [
            {
                "Id_cotize": 91,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 91,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 91,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 91,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 92,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "B200",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Lupe",
        "cotize_Apellidos": "esparza",
        "cotize_FechaNac": "1987-09-19T00:00:00",
        "cotize_correo": "lala@kdl.com",
        "cotize_telefono": "78906789",
        "cotize_CP": 98765,
        "Opciones": [
            {
                "Id_cotize": 92,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 92,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 92,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 92,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 93,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "MONDEO",
        "Anio": 2022,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Luis",
        "cotize_Apellidos": "figo",
        "cotize_FechaNac": "1972-06-19T00:00:00",
        "cotize_correo": "figo@lla.com",
        "cotize_telefono": "234567890",
        "cotize_CP": 56776,
        "Opciones": [
            {
                "Id_cotize": 93,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 93,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 93,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 93,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 94,
        "NombreTipo": "AUTO",
        "NombreMarca": "JAGUAR",
        "NombreModelo": "XE",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Carlos",
        "cotize_Apellidos": "Gonzales",
        "cotize_FechaNac": "1976-08-19T00:00:00",
        "cotize_correo": "popo@gmail.com",
        "cotize_telefono": "839393939",
        "cotize_CP": 89656,
        "Opciones": [
            {
                "Id_cotize": 94,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 94,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 94,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 94,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 95,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": "FORTE",
        "Anio": 2023,
        "Vehiculo_desc": "LIMITED AUT 4P 4CIL QC",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Matias",
        "cotize_Apellidos": "20/12/1965",
        "cotize_FechaNac": "1965-12-20T00:00:00",
        "cotize_correo": "4567896789",
        "cotize_telefono": "48532",
        "cotize_CP": 48532,
        "Opciones": [
            {
                "Id_cotize": 95,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 95,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 95,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 95,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 96,
        "NombreTipo": "AUTO",
        "NombreMarca": "KIA",
        "NombreModelo": "NITRO",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "garza",
        "cotize_Apellidos": "09/09/1999",
        "cotize_FechaNac": "1999-09-09T00:00:00",
        "cotize_correo": "678907689",
        "cotize_telefono": "67888",
        "cotize_CP": 0,
        "Opciones": []
    },
    {
        "Id_cotize": 97,
        "NombreTipo": "AUTO",
        "NombreMarca": "FORD",
        "NombreModelo": "MONDEO",
        "Anio": 2023,
        "Vehiculo_desc": "AUT 3.6L 6CIL 5P",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "FRANCISCO",
        "cotize_Apellidos": "ESCAMILLA",
        "cotize_FechaNac": "1967-02-09T00:00:00",
        "cotize_correo": "ESCA@HOY.COM",
        "cotize_telefono": "34567890",
        "cotize_CP": 77776,
        "Opciones": [
            {
                "Id_cotize": 97,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 97,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 97,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 97,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    },
    {
        "Id_cotize": 98,
        "NombreTipo": "AUTO",
        "NombreMarca": "FIAT",
        "NombreModelo": "LINEA",
        "Anio": 2023,
        "Vehiculo_desc": "LIMITED AUT 4P 4CIL QC",
        "NombreGenero": "HOMBRE",
        "cotize_Nombre": "Lupe",
        "cotize_Apellidos": "Esparza",
        "cotize_FechaNac": "1965-08-19T00:00:00",
        "cotize_correo": "kdkd@lssl.com",
        "cotize_telefono": "345678999",
        "cotize_CP": 87778,
        "Opciones": [
            {
                "Id_cotize": 98,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 3114.53,
                "costoMensualidad": 2430.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 98,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 1,
                "plan_descr": "AMPLIA",
                "costoPrincipal": 25253.63,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 10% sobre el Valor Comercial",
                "detRespCivilTerc": 1000000.00,
                "detServAsist": true,
                "detGastosMedicos": 40000.00,
                "detAccidAutoCond": 0.00,
                "detExtRespCivil": false,
                "detEliminaDeduc": false,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "",
                "detAutoconsentido": false,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 98,
                "Id_frecuencia": 1,
                "frec_descr": "MENSUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 3484.54,
                "costoMensualidad": 2800.13,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            },
            {
                "Id_cotize": 98,
                "Id_frecuencia": 2,
                "frec_descr": "ANUAL",
                "id_plan": 2,
                "plan_descr": "PLUS",
                "costoPrincipal": 29012.50,
                "costoMensualidad": 0.00,
                "detDanios": "Deducible variable 5% sobre valor comercial",
                "detRoturaCristal": "Amparada 20%",
                "detRoboTotal": "Deducible Variable 5% sobre el Valor Comercial",
                "detRespCivilTerc": 1250000.00,
                "detServAsist": true,
                "detGastosMedicos": 50000.00,
                "detAccidAutoCond": 100000.00,
                "detExtRespCivil": true,
                "detEliminaDeduc": true,
                "detDefensaLegal": true,
                "detRespCivilExceso": 3000000.00,
                "detRoboParcial": "Deducible 25%",
                "detAutoconsentido": true,
                "detRespCivilExtranjero": true
            }
        ]
    }
];

  // , 'actions'
  dataStudentsList = new MatTableDataSource();
  displayedStudentsColumnsList: string[] = ['Id_cotize','NombreTipo','NombreMarca','NombreModelo','Anio','Vehiculo_desc','NombreGenero','cotize_Nombre','cotize_Apellidos','cotize_FechaNac','cotize_correo','cotize_telefono','cotize_CP'];

  
  

  ngOnInit() {
    this.dataStudentsList.data = this.STUDENTS_DATA;
  }

  // Toggel Rows
  toggleTableRows() {
    this.isTableExpanded = !this.isTableExpanded;

    this.dataStudentsList.data.forEach((row: any) => {
      row.isExpanded = this.isTableExpanded;
    })
  }


    
    

}


export class DialogContentExampleDialog {}
